# build con python3
[phases.setup]
aptPkgs = ['fonts-dejavu-core', 'python3', 'python3-pip', 'libreoffice']

[phases.install]
cmds = ['npm install', 'pip install reportlab python-pptx openpyxl --break-system-packages']

[start]
cmd = 'node server.js'
